[build]
  base = "/"
  command = "npm install && npm run generate"
  publish = ".output/public"
  environment = { NODE_VERSION = "18" }

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"